[package]
name = "aoc-2019-rust"
version = "0.1.0"
authors = ["Fotis Papadogeorgopoulos <fotis@futurice.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
